dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^9.2.0
  # Bloc for state management
  flutter_bloc: ^9.1.1
  # Value equality
  # ...
  shared_preferences: ^2.5.4
  # Geolocation
  url_launcher: ^6.3.2

dev_dependencies:
  # Warnings
  flutter_lints: ^6.0.0