name: etsAndroid
description: Android Clean Architecture 

version: 1.0.0+1

environment:
  sdk: '>=2.6.0 <3.7.0'

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^8.0.2
  # Bloc for state management
  flutter_bloc: ^9.1.1
  # Value equality
  equatable: ^2.0.8
  # Functional programming thingies
  dartz: ^0.10.1
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.12.0+3
  # Local cache
  shared_preferences: ^2.5.4
  # Geolocation
  url_launcher: ^6.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.6.3

flutter:
  uses-material-design: true  